// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs3EdYS9lFC3qXRLRLwBNDv3WzdnIKnJs',
    appId: '1:946890937033:android:756c8dce069f5c76c57318',
    messagingSenderId: '946890937033',
    projectId: 'databootng-ffdd3',
    storageBucket: 'databootng-ffdd3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEILPg5b7IUfogCVygSbzmRxxHrCa_iic',
    appId: '1:946890937033:ios:e60b869c3b3a75bdc57318',
    messagingSenderId: '946890937033',
    projectId: 'databootng-ffdd3',
    storageBucket: 'databootng-ffdd3.firebasestorage.app',
    iosBundleId: 'com.example.finWise',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEILPg5b7IUfogCVygSbzmRxxHrCa_iic',
    appId: '1:946890937033:ios:e60b869c3b3a75bdc57318',
    messagingSenderId: '946890937033',
    projectId: 'databootng-ffdd3',
    storageBucket: 'databootng-ffdd3.firebasestorage.app',
    iosBundleId: 'com.example.finWise',
  );
}
